apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: staging
namePrefix: staging-

resources:
  - ../../base
  - namespace.yml

patches:
  - path: app-patches.yml
  - path: ingress-patch.yml

images:
  - name: atkaridarshan04/bookstore-frontend
    newTag: v2
  - name: atkaridarshan04/bookstore-backend
    newTag: v2

configMapGenerator:
  - name: backend-config
    literals:
      - PORT=8000
      - mongoDBURL=mongodb://admin:password123@staging-mongodb-deployment-0.staging-mongodb-service-headless.staging.svc.cluster.local:27017/db?authSource=admin
