---
apiVersion: v1
kind: ConfigMap 
metadata:
  name: {{ .Release.Name }}-backend-config
  namespace: {{ .Values.namespace }}
data:
  PORT: "{{ .Values.backend.containerPort }}"
  mongoDBURL: "mongodb://{{ .Values.mongodb.username }}:{{ .Values.mongodb.password }}@{{ .Release.Name }}-mongodb-statefulset-0.{{ .Release.Name }}-{{ .Values.mongodb.serviceName }}.{{ .Values.namespace }}.svc.cluster.local:27017/{{ .Values.mongodb.dbName }}?authSource={{ .Values.mongodb.authSource }}"

---
apiVersion: v1 
kind: Service 
metadata: 
  name: {{ .Release.Name }}-backend-service
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.backend.service.type }}
  selector:
    app: backend
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.containerPort }}
      protocol: TCP
      # nodePort: {{ .Values.backend.service.nodePort }}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-backend-deployment
  namespace: {{ .Values.namespace }}
  labels:
    app: backend
spec:
  replicas: {{ .Values.backend.replicas }}
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      name: 
      labels:
        app: backend
    spec:
      containers:
        - name: backend 
          image: {{ .Values.backend.image }}
          ports:
            - containerPort: {{ .Values.backend.containerPort }}
          envFrom:
            - configMapRef: 
                name: {{ .Release.Name }}-backend-config
          livenessProbe:
            httpGet: 
              path: /books 
              port: {{ .Values.backend.containerPort }}
            initialDelaySeconds: {{ .Values.backend.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.backend.livenessProbe.periodSeconds }}
          readinessProbe:
            httpGet:
              path: /books
              port: {{ .Values.backend.containerPort }}
            initialDelaySeconds: {{ .Values.backend.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.backend.readinessProbe.periodSeconds }}
  strategy:
    type: {{ .Values.backend.strategy.type }}
    rollingUpdate:
      maxSurge: {{ .Values.backend.strategy.rollingUpdate.maxSurge }}
      maxUnavailable: {{ .Values.backend.strategy.rollingUpdate.maxUnavailable }}
