---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-mongodb-secret
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  username: {{ .Values.mongodb.username | b64enc }}
  password: {{ .Values.mongodb.password | b64enc }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-mongodb-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: mongodb
  clusterIP: None
  ports:
    - port: 27017
      targetPort: 27017
      protocol: TCP

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-mongodb-statefulset
  namespace: {{ .Values.namespace }}
  labels:
    app: mongodb
spec:
  replicas: {{ .Values.mongodb.replicas }}
  serviceName: {{ .Release.Name }}-mongodb-service
  selector:
    matchLabels:
      app: mongodb
  updateStrategy:
    type: RollingUpdate   
    rollingUpdate:
      partition: 0
  template:
    metadata:
      name: mongodb
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: {{ .Values.mongodb.image }}
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-mongodb-secret
                  key: username
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-mongodb-secret
                  key: password
            - name: MONGO_INITDB_DATABASE
              value: {{ .Values.mongodb.dbName }}
          volumeMounts:
            - name: mongodb-vol
              mountPath: /data/db        
      volumes:
        - name: mongodb-vol
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-mongo-pvc
